import type { Bloom, Subject } from '../domain/types.js';

export interface SeedConcept {
  slug: string;
  label: string;
  subject: Subject;
  grades: [number, number];
  difficulty: number;
  bloom?: Bloom;
  description: string;
  requires?: string[];
  leadsTo?: string[];
  relatedTo?: string[];
  contrastsWith?: string[];
  appliesTo?: string[];
  tags?: string[];
  standards?: string[];
  terms?: [string, string][];
}

/** A real, connected K-12 curriculum spine. Enough graph to demonstrate
 *  prerequisite tracing, ZPD frontiers, centrality and repair routing without
 *  anyone having to upload a textbook first. */
export const SEED_CONCEPTS: SeedConcept[] = [
  /* ============================= MATHEMATICS ============================= */
  { slug: 'counting', label: 'Counting and Cardinality', subject: 'math', grades: [0, 1], difficulty: 0.05,
    bloom: 'remember', description: 'Saying number names in order and knowing the last word tells you how many.',
    tags: ['number sense'], terms: [['cardinality', 'how many things are in a group']] },
  { slug: 'place-value', label: 'Place Value', subject: 'math', grades: [1, 4], difficulty: 0.18,
    description: 'The position of a digit decides its value: the 3 in 30 means three tens.',
    requires: ['counting'], tags: ['number sense'],
    terms: [['digit', 'a single number symbol from 0 to 9'], ['place value', 'what a digit is worth because of where it sits']] },
  { slug: 'addition', label: 'Addition', subject: 'math', grades: [1, 3], difficulty: 0.15,
    description: 'Putting groups together to find a total.', requires: ['counting'], tags: ['operations'],
    terms: [['sum', 'the answer when you add'], ['addend', 'a number being added']] },
  { slug: 'subtraction', label: 'Subtraction', subject: 'math', grades: [1, 3], difficulty: 0.2,
    description: 'Taking away, or finding the difference between two amounts.',
    requires: ['addition'], contrastsWith: ['addition'], tags: ['operations'],
    terms: [['difference', 'the gap between two numbers']] },
  { slug: 'multiplication', label: 'Multiplication', subject: 'math', grades: [2, 4], difficulty: 0.3,
    description: 'Repeated addition of equal groups, or the area of a rectangle of rows and columns.',
    requires: ['addition', 'place-value'], tags: ['operations'],
    terms: [['factor', 'a number being multiplied'], ['product', 'the answer when you multiply']] },
  { slug: 'division', label: 'Division', subject: 'math', grades: [3, 5], difficulty: 0.4,
    description: 'Splitting a total into equal groups, or asking how many groups fit.',
    requires: ['multiplication', 'subtraction'], contrastsWith: ['multiplication'], tags: ['operations'],
    terms: [['quotient', 'the answer when you divide'], ['remainder', 'what is left over']] },
  { slug: 'factors-multiples', label: 'Factors and Multiples', subject: 'math', grades: [4, 6], difficulty: 0.38,
    description: 'Factors divide a number exactly; multiples are what you land on when you skip-count.',
    requires: ['division'], tags: ['number theory'] },
  { slug: 'fractions', label: 'Fractions', subject: 'math', grades: [3, 6], difficulty: 0.52,
    description: 'A fraction names equal parts of one whole: the denominator says how many parts, the numerator how many you have.',
    requires: ['division'], tags: ['rational numbers'],
    terms: [['numerator', 'the top number: how many parts you have'], ['denominator', 'the bottom number: how many equal parts the whole is cut into']] },
  { slug: 'equivalent-fractions', label: 'Equivalent Fractions', subject: 'math', grades: [4, 6], difficulty: 0.55,
    description: 'Different fractions can name the same amount, because multiplying top and bottom by the same number does not change the size.',
    requires: ['fractions', 'factors-multiples'], tags: ['rational numbers'] },
  { slug: 'fraction-addition', label: 'Adding and Subtracting Fractions', subject: 'math', grades: [4, 7], difficulty: 0.62,
    description: 'You can only add parts that are the same size, so unlike denominators must be made common first.',
    requires: ['equivalent-fractions', 'addition'], tags: ['rational numbers'] },
  { slug: 'fraction-multiplication', label: 'Multiplying and Dividing Fractions', subject: 'math', grades: [5, 7], difficulty: 0.65,
    description: 'Multiplying fractions takes a part of a part; dividing by a fraction asks how many of them fit.',
    requires: ['fractions', 'multiplication'], tags: ['rational numbers'] },
  { slug: 'decimals', label: 'Decimals', subject: 'math', grades: [4, 6], difficulty: 0.48,
    description: 'Place value continued past the ones place, so tenths and hundredths get their own columns.',
    requires: ['place-value', 'fractions'], relatedTo: ['fractions'], tags: ['rational numbers'] },
  { slug: 'percentages', label: 'Percentages', subject: 'math', grades: [5, 8], difficulty: 0.55,
    description: 'A percentage is a fraction with a denominator of one hundred.',
    requires: ['decimals', 'fractions'], tags: ['rational numbers'] },
  { slug: 'ratios', label: 'Ratios', subject: 'math', grades: [6, 8], difficulty: 0.6,
    description: 'A ratio compares two quantities by division rather than by difference.',
    requires: ['fractions', 'division'], tags: ['proportional reasoning'],
    terms: [['ratio', 'a comparison of two amounts using division']] },
  { slug: 'proportions', label: 'Proportional Reasoning', subject: 'math', grades: [6, 9], difficulty: 0.68,
    description: 'Two ratios are proportional when scaling one quantity scales the other by the same factor.',
    requires: ['ratios', 'equivalent-fractions'], tags: ['proportional reasoning'] },
  { slug: 'unit-rates', label: 'Unit Rates', subject: 'math', grades: [6, 8], difficulty: 0.58,
    description: 'A rate rewritten so the second quantity is one: miles per hour, cost per gram.',
    requires: ['ratios'], appliesTo: ['speed'], tags: ['proportional reasoning'] },
  { slug: 'integers', label: 'Negative Numbers', subject: 'math', grades: [5, 7], difficulty: 0.5,
    description: 'Numbers below zero, measured as a direction and a distance from zero.',
    requires: ['subtraction'], tags: ['number sense'],
    terms: [['integer', 'a whole number, positive, negative or zero'], ['absolute value', 'the distance from zero, ignoring direction']] },
  { slug: 'order-of-operations', label: 'Order of Operations', subject: 'math', grades: [5, 8], difficulty: 0.45,
    description: 'An agreed sequence for evaluating an expression so everyone gets the same answer.',
    requires: ['multiplication', 'addition'], tags: ['algebra readiness'] },
  { slug: 'exponents', label: 'Exponents', subject: 'math', grades: [6, 9], difficulty: 0.58,
    description: 'Repeated multiplication written compactly; the exponent counts the factors.',
    requires: ['multiplication', 'order-of-operations'], tags: ['algebra readiness'] },
  { slug: 'square-roots', label: 'Square Roots', subject: 'math', grades: [7, 9], difficulty: 0.62,
    description: 'The side length that produces a given square area - the inverse of squaring.',
    requires: ['exponents'], contrastsWith: ['exponents'], tags: ['algebra readiness'] },
  { slug: 'variables', label: 'Variables and Expressions', subject: 'math', grades: [6, 8], difficulty: 0.55,
    description: 'A letter standing for an unknown or changing quantity.',
    requires: ['order-of-operations', 'integers'], tags: ['algebra'],
    terms: [['variable', 'a letter that holds a number you do not know yet'], ['coefficient', 'the number multiplying a variable']] },
  { slug: 'linear-equations', label: 'Solving Linear Equations', subject: 'math', grades: [7, 9], difficulty: 0.7,
    description: 'Undoing operations in reverse order to isolate the unknown, keeping both sides balanced.',
    requires: ['variables', 'integers', 'fraction-multiplication'], tags: ['algebra'] },
  { slug: 'inequalities', label: 'Inequalities', subject: 'math', grades: [7, 10], difficulty: 0.68,
    description: 'Statements about ranges rather than single values; multiplying by a negative flips the direction.',
    requires: ['linear-equations', 'integers'], tags: ['algebra'] },
  { slug: 'coordinate-plane', label: 'The Coordinate Plane', subject: 'math', grades: [5, 8], difficulty: 0.42,
    description: 'Two number lines crossing at zero, so any point gets an address.',
    requires: ['integers'], tags: ['geometry', 'algebra'] },
  { slug: 'slope', label: 'Slope and Rate of Change', subject: 'math', grades: [7, 10], difficulty: 0.72,
    description: 'How steeply a line rises for each step right: the constant rate of change.',
    requires: ['coordinate-plane', 'unit-rates', 'proportions'], appliesTo: ['speed'], tags: ['algebra'] },
  { slug: 'linear-functions', label: 'Linear Functions', subject: 'math', grades: [8, 10], difficulty: 0.78,
    description: 'Relationships with a constant rate of change, written y = mx + b.',
    requires: ['slope', 'linear-equations'], tags: ['algebra', 'functions'] },
  { slug: 'systems-equations', label: 'Systems of Equations', subject: 'math', grades: [8, 11], difficulty: 0.82,
    description: 'Two conditions at once; the solution is where the lines meet.',
    requires: ['linear-functions'], tags: ['algebra'] },
  { slug: 'quadratics', label: 'Quadratic Functions', subject: 'math', grades: [9, 11], difficulty: 0.85,
    description: 'Relationships where the rate of change itself changes at a constant rate, producing a parabola.',
    requires: ['linear-functions', 'exponents', 'square-roots'], tags: ['algebra', 'functions'] },
  { slug: 'factoring', label: 'Factoring Polynomials', subject: 'math', grades: [9, 11], difficulty: 0.83,
    description: 'Rewriting a sum as a product, so the zero-product property can find roots.',
    requires: ['quadratics', 'factors-multiples'], tags: ['algebra'] },
  { slug: 'perimeter-area', label: 'Perimeter and Area', subject: 'math', grades: [3, 6], difficulty: 0.35,
    description: 'Perimeter measures the boundary; area measures the covering.',
    requires: ['multiplication', 'addition'], contrastsWith: ['perimeter-area'], tags: ['geometry'] },
  { slug: 'volume', label: 'Volume', subject: 'math', grades: [5, 8], difficulty: 0.5,
    description: 'How many unit cubes fill a solid.', requires: ['perimeter-area', 'multiplication'], tags: ['geometry'] },
  { slug: 'angles', label: 'Angles', subject: 'math', grades: [4, 7], difficulty: 0.38,
    description: 'The amount of turn between two rays sharing an endpoint.', requires: ['counting'], tags: ['geometry'] },
  { slug: 'triangles', label: 'Triangle Properties', subject: 'math', grades: [6, 9], difficulty: 0.55,
    description: 'Three sides, three angles summing to 180 degrees, and strict rules about which side lengths can close.',
    requires: ['angles'], tags: ['geometry'] },
  { slug: 'pythagoras', label: 'The Pythagorean Theorem', subject: 'math', grades: [8, 10], difficulty: 0.72,
    description: 'In a right triangle the squares on the legs add to the square on the hypotenuse.',
    requires: ['triangles', 'square-roots', 'exponents'], tags: ['geometry'],
    terms: [['hypotenuse', 'the longest side of a right triangle, opposite the right angle']] },
  { slug: 'similarity', label: 'Similarity and Scale', subject: 'math', grades: [7, 10], difficulty: 0.7,
    description: 'Same shape, different size: corresponding angles equal and sides in proportion.',
    requires: ['proportions', 'triangles'], tags: ['geometry'] },
  { slug: 'mean-median-mode', label: 'Measures of Centre', subject: 'math', grades: [4, 7], difficulty: 0.4,
    description: 'Three different answers to "what is typical": the balance point, the middle value and the most common.',
    requires: ['division', 'addition'], tags: ['statistics'] },
  { slug: 'data-displays', label: 'Reading Data Displays', subject: 'math', grades: [3, 7], difficulty: 0.32,
    description: 'Bar charts, line graphs and dot plots each answer a different kind of question.',
    requires: ['counting'], tags: ['statistics'] },
  { slug: 'probability', label: 'Probability', subject: 'math', grades: [6, 9], difficulty: 0.6,
    description: 'A number from 0 to 1 measuring how often an outcome happens in the long run.',
    requires: ['fractions', 'percentages'], tags: ['statistics'] },
  { slug: 'variability', label: 'Spread and Variability', subject: 'math', grades: [7, 10], difficulty: 0.65,
    description: 'Two data sets can share a mean and feel completely different; spread says how much.',
    requires: ['mean-median-mode'], tags: ['statistics'] },

  { slug: 'word-problems', label: 'Mathematical Word Problems', subject: 'math', grades: [4, 10], difficulty: 0.72,
    description: 'Turning a sentence into a model: find the quantities, name the unknown, choose the operation, then check the answer against the story.',
    requires: ['comprehension', 'variables'], tags: ['algebra', 'reading'],
    terms: [['model', 'the equation or diagram that stands in for the story']] },

  /* =============================== PHYSICS =============================== */
  { slug: 'measurement', label: 'Measurement and Units', subject: 'physics', grades: [4, 7], difficulty: 0.3,
    description: 'Every physical quantity needs a number and a unit; comparing requires matching units.',
    requires: ['decimals'], tags: ['foundations'],
    terms: [['unit', 'the agreed size you are counting'], ['SI units', 'the shared international set of units']] },
  { slug: 'motion', label: 'Describing Motion', subject: 'physics', grades: [5, 9], difficulty: 0.42,
    description: 'Position, distance and displacement - where something is and how far it moved.',
    requires: ['measurement', 'coordinate-plane'], tags: ['mechanics'] },
  { slug: 'speed', label: 'Speed and Velocity', subject: 'physics', grades: [6, 9], difficulty: 0.55,
    description: 'Distance covered per unit time; velocity adds direction.',
    requires: ['motion', 'unit-rates'], contrastsWith: ['acceleration'], tags: ['mechanics'],
    terms: [['velocity', 'speed with a direction attached']] },
  { slug: 'acceleration', label: 'Acceleration', subject: 'physics', grades: [7, 10], difficulty: 0.68,
    description: 'How quickly velocity changes - including slowing down and turning.',
    requires: ['speed', 'slope'], contrastsWith: ['speed'], tags: ['mechanics'] },
  { slug: 'forces', label: 'Forces', subject: 'physics', grades: [6, 10], difficulty: 0.6,
    description: 'A push or pull with size and direction; forces add as vectors.',
    requires: ['measurement'], tags: ['mechanics'],
    terms: [['newton', 'the unit of force'], ['net force', 'what is left after all forces are combined']] },
  { slug: 'newtons-first-law', label: "Newton's First Law", subject: 'physics', grades: [7, 11], difficulty: 0.65,
    description: 'Without a net force, motion does not change - objects keep doing what they were doing.',
    requires: ['forces', 'speed'], tags: ['mechanics'],
    terms: [['inertia', 'the tendency of matter to keep its current motion']] },
  { slug: 'newtons-second-law', label: "Newton's Second Law", subject: 'physics', grades: [8, 11], difficulty: 0.78,
    description: 'Net force equals mass times acceleration, so the same push moves a heavy thing less.',
    requires: ['newtons-first-law', 'acceleration', 'linear-equations'], tags: ['mechanics'] },
  { slug: 'newtons-third-law', label: "Newton's Third Law", subject: 'physics', grades: [7, 11], difficulty: 0.7,
    description: 'Forces come in pairs: equal in size, opposite in direction, acting on different objects.',
    requires: ['forces'], tags: ['mechanics'] },
  { slug: 'friction', label: 'Friction', subject: 'physics', grades: [6, 10], difficulty: 0.55,
    description: 'A contact force opposing sliding, depending on surfaces and how hard they press together.',
    requires: ['forces'], tags: ['mechanics'] },
  { slug: 'gravity', label: 'Gravity', subject: 'physics', grades: [5, 11], difficulty: 0.58,
    description: 'An attraction between any two masses; near Earth it gives everything the same downward acceleration.',
    requires: ['forces'], tags: ['mechanics', 'astronomy'] },
  { slug: 'energy', label: 'Energy', subject: 'physics', grades: [6, 10], difficulty: 0.62,
    description: 'The capacity to cause change, transferred between stores but never created or destroyed.',
    requires: ['measurement'], tags: ['energy'],
    terms: [['joule', 'the unit of energy'], ['kinetic energy', 'energy a thing has because it is moving']] },
  { slug: 'work-power', label: 'Work and Power', subject: 'physics', grades: [8, 11], difficulty: 0.72,
    description: 'Work is force acting through a distance; power is how fast that happens.',
    requires: ['energy', 'forces', 'multiplication'], tags: ['energy'] },
  { slug: 'energy-conservation', label: 'Conservation of Energy', subject: 'physics', grades: [7, 11], difficulty: 0.75,
    description: 'Total energy in a closed system stays constant; it only changes form.',
    requires: ['energy'], tags: ['energy'] },
  { slug: 'heat-transfer', label: 'Heat Transfer', subject: 'physics', grades: [5, 9], difficulty: 0.5,
    description: 'Thermal energy moves by conduction, convection and radiation, always from hotter to colder.',
    requires: ['energy'], tags: ['thermal'] },
  { slug: 'temperature', label: 'Temperature vs Heat', subject: 'physics', grades: [5, 9], difficulty: 0.52,
    description: 'Temperature measures average particle energy; heat is the energy actually transferred.',
    requires: ['heat-transfer'], contrastsWith: ['heat-transfer'], tags: ['thermal'] },
  { slug: 'waves', label: 'Waves', subject: 'physics', grades: [6, 10], difficulty: 0.6,
    description: 'A travelling disturbance that carries energy without carrying matter along with it.',
    requires: ['energy'], tags: ['waves'],
    terms: [['amplitude', 'how big the disturbance is'], ['wavelength', 'the distance between repeats'], ['frequency', 'how many repeats pass per second']] },
  { slug: 'sound', label: 'Sound', subject: 'physics', grades: [5, 9], difficulty: 0.5,
    description: 'A pressure wave in a material; no material means no sound.',
    requires: ['waves'], tags: ['waves'] },
  { slug: 'light', label: 'Light and Optics', subject: 'physics', grades: [5, 10], difficulty: 0.58,
    description: 'Light travels in straight lines until something reflects, refracts or absorbs it.',
    requires: ['waves'], tags: ['waves', 'optics'] },
  { slug: 'lenses', label: 'Lenses and Images', subject: 'physics', grades: [8, 11], difficulty: 0.72,
    description: 'Curved surfaces bend light to a focus, forming real or virtual images.',
    requires: ['light', 'similarity'], tags: ['optics'] },
  { slug: 'current-electricity', label: 'Electric Current', subject: 'physics', grades: [6, 10], difficulty: 0.62,
    description: 'Charge flowing round a complete loop, driven by a voltage difference.',
    requires: ['energy'], tags: ['electricity'],
    terms: [['current', 'the rate charge flows, in amperes'], ['voltage', 'the energy given to each unit of charge']] },
  { slug: 'circuits', label: 'Series and Parallel Circuits', subject: 'physics', grades: [7, 11], difficulty: 0.7,
    description: 'One path shares current; branching paths share voltage.',
    requires: ['current-electricity'], tags: ['electricity'] },
  { slug: 'ohms-law', label: "Ohm's Law", subject: 'physics', grades: [8, 11], difficulty: 0.72,
    description: 'For many conductors, current is proportional to voltage and inversely proportional to resistance.',
    requires: ['circuits', 'proportions', 'linear-equations'], tags: ['electricity'] },
  { slug: 'magnetism', label: 'Magnetism', subject: 'physics', grades: [6, 11], difficulty: 0.6,
    description: 'Moving charge creates magnetic fields, and magnetic fields push moving charge.',
    requires: ['current-electricity'], tags: ['electricity'] },

  /* ============================== CHEMISTRY ============================== */
  { slug: 'matter-states', label: 'States of Matter', subject: 'chemistry', grades: [3, 7], difficulty: 0.28,
    description: 'Solid, liquid and gas differ in how tightly particles are held and how freely they move.',
    requires: ['measurement'], tags: ['particles'] },
  { slug: 'particle-model', label: 'The Particle Model', subject: 'chemistry', grades: [5, 9], difficulty: 0.48,
    description: 'All matter is made of tiny particles in constant motion; their arrangement explains the states.',
    requires: ['matter-states'], tags: ['particles'] },
  { slug: 'atoms', label: 'Atomic Structure', subject: 'chemistry', grades: [7, 11], difficulty: 0.65,
    description: 'A dense nucleus of protons and neutrons surrounded by electrons in shells.',
    requires: ['particle-model'], tags: ['atomic'],
    terms: [['proton', 'a positive particle in the nucleus'], ['electron', 'a negative particle outside the nucleus'], ['neutron', 'a neutral particle in the nucleus']] },
  { slug: 'periodic-table', label: 'The Periodic Table', subject: 'chemistry', grades: [7, 11], difficulty: 0.6,
    description: 'Elements ordered by proton number, with columns sharing outer-shell behaviour.',
    requires: ['atoms'], tags: ['atomic'] },
  { slug: 'bonding', label: 'Chemical Bonding', subject: 'chemistry', grades: [8, 12], difficulty: 0.75,
    description: 'Atoms transfer or share electrons to reach stable arrangements.',
    requires: ['periodic-table', 'atoms'], tags: ['bonding'] },
  { slug: 'chemical-reactions', label: 'Chemical Reactions', subject: 'chemistry', grades: [6, 11], difficulty: 0.65,
    description: 'Bonds break and reform, rearranging atoms into new substances.',
    requires: ['particle-model'], tags: ['reactions'] },
  { slug: 'conservation-mass', label: 'Conservation of Mass', subject: 'chemistry', grades: [7, 11], difficulty: 0.62,
    description: 'Atoms are rearranged, never lost, so total mass is unchanged by a reaction.',
    requires: ['chemical-reactions'], tags: ['reactions'] },
  { slug: 'balancing-equations', label: 'Balancing Chemical Equations', subject: 'chemistry', grades: [8, 12], difficulty: 0.8,
    description: 'Adjusting coefficients until every element has equal atom counts on both sides.',
    requires: ['conservation-mass', 'bonding', 'factors-multiples'], tags: ['reactions'] },
  { slug: 'acids-bases', label: 'Acids and Bases', subject: 'chemistry', grades: [7, 12], difficulty: 0.68,
    description: 'Acids release hydrogen ions, bases accept them; pH measures the concentration on a log scale.',
    requires: ['chemical-reactions'], tags: ['reactions'] },
  { slug: 'solutions', label: 'Solutions and Concentration', subject: 'chemistry', grades: [6, 11], difficulty: 0.6,
    description: 'A solute spread evenly through a solvent; concentration is amount per volume.',
    requires: ['particle-model', 'ratios'], tags: ['mixtures'] },

  /* =============================== BIOLOGY =============================== */
  { slug: 'living-things', label: 'Characteristics of Living Things', subject: 'biology', grades: [1, 5], difficulty: 0.2,
    description: 'Living things move, respire, respond, grow, reproduce, excrete and feed.',
    tags: ['foundations'] },
  { slug: 'cells', label: 'Cells', subject: 'biology', grades: [4, 9], difficulty: 0.45,
    description: 'The smallest unit that can carry out all life processes.',
    requires: ['living-things'], tags: ['cells'],
    terms: [['nucleus', 'the control centre holding the genetic instructions'], ['membrane', 'the boundary controlling what enters and leaves']] },
  { slug: 'cell-organelles', label: 'Organelles and Their Jobs', subject: 'biology', grades: [6, 10], difficulty: 0.55,
    description: 'Each structure inside a cell has a specialised function.',
    requires: ['cells'], tags: ['cells'] },
  { slug: 'diffusion', label: 'Diffusion and Osmosis', subject: 'biology', grades: [7, 11], difficulty: 0.65,
    description: 'Particles spread from high to low concentration without needing energy.',
    requires: ['cells', 'particle-model', 'solutions'], tags: ['transport'] },
  { slug: 'photosynthesis', label: 'Photosynthesis', subject: 'biology', grades: [5, 11], difficulty: 0.6,
    description: 'Plants capture light energy and build glucose from carbon dioxide and water.',
    requires: ['cell-organelles', 'chemical-reactions', 'energy'], contrastsWith: ['respiration'], tags: ['energy flow'],
    terms: [['chlorophyll', 'the green pigment that captures light'], ['glucose', 'the sugar a plant builds and stores']] },
  { slug: 'respiration', label: 'Cellular Respiration', subject: 'biology', grades: [6, 11], difficulty: 0.65,
    description: 'Releasing energy from glucose, in every living cell, all the time.',
    requires: ['cell-organelles', 'chemical-reactions'], contrastsWith: ['photosynthesis'], tags: ['energy flow'] },
  { slug: 'food-chains', label: 'Food Chains and Webs', subject: 'biology', grades: [3, 8], difficulty: 0.35,
    description: 'Energy passes from producers to consumers, losing most of itself at each step.',
    requires: ['living-things'], relatedTo: ['photosynthesis'], tags: ['ecology'] },
  { slug: 'ecosystems', label: 'Ecosystems', subject: 'biology', grades: [5, 10], difficulty: 0.5,
    description: 'Living and non-living parts interacting, with populations limited by resources.',
    requires: ['food-chains'], tags: ['ecology'] },
  { slug: 'human-body-systems', label: 'Human Body Systems', subject: 'biology', grades: [4, 9], difficulty: 0.45,
    description: 'Organs grouped by function: circulation, digestion, breathing, nerves.',
    requires: ['cells'], tags: ['physiology'] },
  { slug: 'circulatory-system', label: 'The Circulatory System', subject: 'biology', grades: [6, 10], difficulty: 0.5,
    description: 'A double pump and a closed loop of vessels delivering oxygen and collecting waste.',
    requires: ['human-body-systems', 'respiration'], tags: ['physiology'] },
  { slug: 'dna', label: 'DNA and Genes', subject: 'biology', grades: [7, 12], difficulty: 0.7,
    description: 'A coded molecule whose sequence instructs the building of proteins.',
    requires: ['cell-organelles'], tags: ['genetics'],
    terms: [['gene', 'a section of DNA coding for one trait or protein'], ['chromosome', 'a long packaged strand of DNA']] },
  { slug: 'inheritance', label: 'Inheritance', subject: 'biology', grades: [7, 12], difficulty: 0.72,
    description: 'Offspring receive one allele of each gene from each parent.',
    requires: ['dna', 'probability'], tags: ['genetics'],
    terms: [['allele', 'one version of a gene'], ['dominant', 'an allele that shows even when only one copy is present']] },
  { slug: 'punnett-squares', label: 'Punnett Squares', subject: 'biology', grades: [8, 12], difficulty: 0.7,
    description: 'A grid predicting the probability of each offspring genotype.',
    requires: ['inheritance', 'probability'], tags: ['genetics'] },
  { slug: 'evolution', label: 'Natural Selection', subject: 'biology', grades: [7, 12], difficulty: 0.75,
    description: 'Inherited variation plus differential survival shifts population traits over generations.',
    requires: ['inheritance', 'ecosystems'], tags: ['evolution'] },

  /* ============================ EARTH SCIENCE ============================ */
  { slug: 'water-cycle', label: 'The Water Cycle', subject: 'earth_science', grades: [5, 8], difficulty: 0.32,
    description: 'Water moves between ocean, air and land by evaporation, condensation and precipitation.',
    requires: ['matter-states', 'heat-transfer'], tags: ['systems'] },
  { slug: 'rock-cycle', label: 'The Rock Cycle', subject: 'earth_science', grades: [4, 9], difficulty: 0.4,
    description: 'Heat, pressure, weathering and time convert rock between igneous, sedimentary and metamorphic.',
    requires: ['matter-states'], tags: ['systems'] },
  { slug: 'plate-tectonics', label: 'Plate Tectonics', subject: 'earth_science', grades: [6, 11], difficulty: 0.58,
    description: 'Rigid plates drift on a convecting mantle, building mountains and triggering quakes at their edges.',
    requires: ['rock-cycle', 'heat-transfer'], tags: ['systems'] },
  { slug: 'weather-climate', label: 'Weather and Climate', subject: 'earth_science', grades: [4, 10], difficulty: 0.5,
    description: 'Weather is today, climate is the long-run pattern; both are driven by uneven heating.',
    requires: ['water-cycle', 'heat-transfer'], tags: ['atmosphere'] },
  { slug: 'solar-system', label: 'The Solar System', subject: 'earth_science', grades: [5, 9], difficulty: 0.35,
    description: 'Planets orbiting a star, held by gravity, at hugely different scales and distances.',
    requires: ['gravity'], tags: ['astronomy'] },
  { slug: 'seasons', label: 'Why We Have Seasons', subject: 'earth_science', grades: [4, 9], difficulty: 0.48,
    description: 'Axial tilt changes the angle and duration of sunlight, not our distance from the Sun.',
    requires: ['solar-system', 'angles'], tags: ['astronomy'] },
  { slug: 'moon-phases', label: 'Phases of the Moon', subject: 'earth_science', grades: [5, 8], difficulty: 0.45,
    description: 'We see different fractions of the lit half of the Moon as it orbits Earth.',
    requires: ['solar-system', 'light'], tags: ['astronomy'] },

  /* ============================== COMPUTING ============================== */
  { slug: 'algorithms', label: 'Algorithms', subject: 'computing', grades: [3, 10], difficulty: 0.35,
    description: 'A precise, finite sequence of steps that solves a class of problems.',
    tags: ['foundations'] },
  { slug: 'sequencing', label: 'Sequence, Selection, Repetition', subject: 'computing', grades: [4, 9], difficulty: 0.4,
    description: 'The three control structures every program is built from.',
    requires: ['algorithms'], tags: ['programming'] },
  { slug: 'variables-programming', label: 'Variables in Programs', subject: 'computing', grades: [5, 10], difficulty: 0.45,
    description: 'Named storage whose contents can change as a program runs.',
    requires: ['sequencing'], relatedTo: ['variables'], tags: ['programming'] },
  { slug: 'binary', label: 'Binary Representation', subject: 'computing', grades: [6, 11], difficulty: 0.55,
    description: 'Place value with only two digits, which is how machines store everything.',
    requires: ['place-value', 'exponents'], tags: ['data'] },
  { slug: 'boolean-logic', label: 'Boolean Logic', subject: 'computing', grades: [6, 11], difficulty: 0.55,
    description: 'AND, OR and NOT combine true/false values into decisions.',
    requires: ['sequencing'], tags: ['logic'] },
  { slug: 'functions-programming', label: 'Functions and Decomposition', subject: 'computing', grades: [6, 11], difficulty: 0.6,
    description: 'Naming a block of work so it can be reused and reasoned about separately.',
    requires: ['variables-programming'], tags: ['programming'] },

  /* ================================ ENGLISH =============================== */
  { slug: 'phonemic-awareness', label: 'Phonemic Awareness', subject: 'english', grades: [0, 2], difficulty: 0.15,
    description: 'Hearing and manipulating the individual sounds inside spoken words.',
    tags: ['reading'] },
  { slug: 'phonics', label: 'Phonics and Decoding', subject: 'english', grades: [0, 4], difficulty: 0.3,
    description: 'Mapping letters and letter teams onto sounds to read unfamiliar words.',
    requires: ['phonemic-awareness'], tags: ['reading'] },
  { slug: 'fluency', label: 'Reading Fluency', subject: 'english', grades: [1, 6], difficulty: 0.42,
    description: 'Reading accurately, at a reasonable pace, with expression - which frees attention for meaning.',
    requires: ['phonics'], tags: ['reading'] },
  { slug: 'vocabulary', label: 'Vocabulary and Morphology', subject: 'english', grades: [2, 10], difficulty: 0.5,
    description: 'Using roots, prefixes and suffixes to unlock words you have never seen.',
    requires: ['phonics'], tags: ['reading'] },
  { slug: 'comprehension', label: 'Reading Comprehension', subject: 'english', grades: [2, 12], difficulty: 0.6,
    description: 'Building a mental model of a text: who, what, why and what follows.',
    requires: ['fluency', 'vocabulary'], tags: ['reading'] },
  { slug: 'inference', label: 'Inference', subject: 'english', grades: [4, 12], difficulty: 0.68,
    description: 'Combining text evidence with what you already know to reach an unstated conclusion.',
    requires: ['comprehension'], tags: ['reading'] },
  { slug: 'main-idea', label: 'Main Idea and Supporting Detail', subject: 'english', grades: [3, 10], difficulty: 0.55,
    description: 'Separating the claim a passage makes from the evidence it offers.',
    requires: ['comprehension'], tags: ['reading'] },
  { slug: 'paragraph-structure', label: 'Paragraph Structure', subject: 'english', grades: [3, 10], difficulty: 0.48,
    description: 'One idea per paragraph, stated, developed and linked onward.',
    requires: ['main-idea'], tags: ['writing'] },
  { slug: 'argument-writing', label: 'Argument Writing', subject: 'english', grades: [6, 12], difficulty: 0.7,
    description: 'Claim, evidence, reasoning and a fair treatment of the counter-argument.',
    requires: ['paragraph-structure', 'inference'], tags: ['writing'] },
];

export interface SeedMisconception {
  code: string;
  label: string;
  concept: string;
  subject: Subject;
  severity: 'minor' | 'moderate' | 'critical';
  description: string;
  detector: 'rule' | 'llm' | 'hybrid';
  strategy: string;
  steps: string[];
  wrong?: string;
  right?: string;
  prereqCheck?: string[];
}

/** Documented misconceptions, each with a named repair strategy. */
export const SEED_MISCONCEPTIONS: SeedMisconception[] = [
  { code: 'FRAC_ADD_CROSS', label: 'Adding numerators and denominators separately',
    concept: 'fraction-addition', subject: 'math', severity: 'critical', detector: 'rule',
    description: 'The learner computes a/b + c/d as (a+c)/(b+d), treating the two halves of a fraction as independent numbers.',
    strategy: 'concrete_contradiction',
    steps: [
      'Show 1/2 + 1/2 using their rule: it gives 2/4, which is one half - but two halves make a whole.',
      'Return to a bar model: parts can only be counted when they are the same size.',
      'Re-cut both bars to a common denominator, then count the shaded parts.',
      'Re-test with 2/3 + 1/4 and have the learner narrate why 3/7 cannot be right.',
    ],
    wrong: '2/3 + 1/4 = 3/7', right: '2/3 + 1/4 = 8/12 + 3/12 = 11/12',
    prereqCheck: ['equivalent-fractions', 'factors-multiples'] },

  { code: 'FRAC_BIGGER_DENOM', label: 'Bigger denominator means a bigger fraction',
    concept: 'fractions', subject: 'math', severity: 'moderate', detector: 'rule',
    description: 'Whole-number thinking carried into fractions: 1/8 is judged larger than 1/3 because 8 > 3.',
    strategy: 'visual_comparison',
    steps: [
      'Cut one identical pizza into 3 and another into 8. Which single slice is bigger?',
      'More parts means each part is smaller. The denominator counts the cuts.',
      'Order 1/2, 1/3, 1/4, 1/8 on a number line and say the rule aloud.',
    ],
    wrong: '1/8 > 1/3', right: '1/3 > 1/8' },

  { code: 'DEC_LONGER_BIGGER', label: 'Longer decimal means a bigger number',
    concept: 'decimals', subject: 'math', severity: 'moderate', detector: 'rule',
    description: 'The learner compares decimals by digit count: 0.125 is judged larger than 0.4.',
    strategy: 'place_value_alignment',
    steps: [
      'Line the numbers up by the decimal point, not by length.',
      'Pad with zeros: 0.400 against 0.125. Compare tenths first.',
      'Anchor to money: 0.40 of a dollar versus 0.125 of a dollar.',
    ],
    wrong: '0.125 > 0.4', right: '0.4 > 0.125' },

  { code: 'PEMDAS_LEFT_RIGHT', label: 'Always evaluating left to right',
    concept: 'order-of-operations', subject: 'math', severity: 'moderate', detector: 'rule',
    description: 'The learner ignores operation precedence and simply works across the expression.',
    strategy: 'structure_first',
    steps: [
      'Box the multiplication and division before touching anything else.',
      'Evaluate 2 + 3 x 4 both ways and check against a concrete model of 3 groups of 4.',
      'Rewrite the expression with brackets that make the intended order visible.',
    ],
    wrong: '2 + 3 x 4 = 20', right: '2 + 3 x 4 = 14' },

  { code: 'NEG_SUBTRACT_SMALLER', label: 'Subtracting always makes a number smaller',
    concept: 'integers', subject: 'math', severity: 'moderate', detector: 'rule',
    description: 'Subtracting a negative is treated as subtraction, so 5 - (-3) is computed as 2.',
    strategy: 'number_line_motion',
    steps: [
      'Subtraction is "which way and how far" on the number line.',
      'Taking away a debt of 3 leaves you better off, not worse.',
      'Walk 5 - (-3) on the line: turn around twice, land on 8.',
    ],
    wrong: '5 - (-3) = 2', right: '5 - (-3) = 8' },

  { code: 'ALG_UNBALANCED', label: 'Operating on only one side of an equation',
    concept: 'linear-equations', subject: 'math', severity: 'critical', detector: 'rule',
    description: 'The learner moves a term without applying the inverse operation to both sides.',
    strategy: 'balance_model',
    steps: [
      'Draw the equation as a balance scale. Anything you remove from one pan must leave the other.',
      'Annotate each line with the operation applied to both sides.',
      'Substitute the answer back into the original equation as a habit.',
    ],
    wrong: '2x + 3 = 11 -> 2x = 11 -> x = 5.5', right: '2x + 3 = 11 -> 2x = 8 -> x = 4' },

  { code: 'ALG_LETTER_IS_LABEL', label: 'Treating a variable as a label, not a number',
    concept: 'variables', subject: 'math', severity: 'moderate', detector: 'hybrid',
    description: 'In "3a", a is read as "apples" rather than as a number of apples, so 3a + 2a becomes "5 apples" and a never varies.',
    strategy: 'substitution_drill',
    steps: [
      'Substitute three different values for the letter and watch the expression change.',
      'Name the quantity explicitly: a = the number of apples, not the apple itself.',
      'Contrast 3a with 3 apples in a word problem where a is unknown.',
    ] },

  { code: 'PROP_ADDITIVE', label: 'Using addition where the relationship is multiplicative',
    concept: 'proportions', subject: 'math', severity: 'critical', detector: 'rule',
    description: 'Scaling a recipe from 2 to 3 people by adding 1 to every quantity instead of multiplying by 1.5.',
    strategy: 'ratio_table',
    steps: [
      'Build a ratio table and look for the constant multiplier between rows.',
      'Test the additive rule on an extreme case (2 people to 20) and watch it break.',
      'State the scale factor explicitly before computing anything.',
    ],
    wrong: '2 people need 4 cups, so 3 people need 5 cups', right: '2 people need 4 cups, so 3 people need 6 cups',
    prereqCheck: ['ratios', 'fraction-multiplication'] },

  { code: 'AREA_PERIM_CONFUSION', label: 'Confusing perimeter with area',
    concept: 'perimeter-area', subject: 'math', severity: 'moderate', detector: 'rule',
    description: 'The learner adds side lengths when asked for area, or multiplies when asked for perimeter.',
    strategy: 'physical_contrast',
    steps: [
      'Perimeter is the fence. Area is the grass. Walk one, cover the other.',
      'Tile a rectangle with unit squares and count them, then walk the boundary.',
      'Show two shapes with equal perimeter and different area.',
    ] },

  { code: 'MEAN_IS_MIDDLE', label: 'Believing the mean is always the middle value',
    concept: 'mean-median-mode', subject: 'math', severity: 'minor', detector: 'rule',
    description: 'Mean and median are treated as interchangeable, so outliers are not expected to move the mean.',
    strategy: 'outlier_demo',
    steps: [
      'Compute both for 2, 3, 4, 5, 100 and compare.',
      'The mean is a balance point; one heavy value tips it.',
      'Decide which measure answers the actual question being asked.',
    ] },

  { code: 'PHYS_FORCE_NEEDED_FOR_MOTION', label: 'Motion requires a continuous force',
    concept: 'newtons-first-law', subject: 'physics', severity: 'critical', detector: 'hybrid',
    description: 'The intuitive Aristotelian view: if something is moving there must be a force pushing it right now.',
    strategy: 'remove_the_force',
    steps: [
      'Slide a puck on ice, then on carpet. What changed was friction, not the need for a push.',
      'Imagine removing every force: the puck keeps going. Nothing has to push it.',
      'Separate "what started the motion" from "what keeps it going".',
    ],
    wrong: 'A ball rolling at constant speed must have a forward force on it',
    right: 'A ball at constant velocity has zero net force' },

  { code: 'PHYS_HEAVIER_FALLS_FASTER', label: 'Heavier objects fall faster',
    concept: 'gravity', subject: 'physics', severity: 'moderate', detector: 'hybrid',
    description: 'Weight is assumed to set falling speed, confusing gravitational force with acceleration.',
    strategy: 'controlled_comparison',
    steps: [
      'Drop a textbook and a sheet of paper, then the same paper crumpled. What actually changed?',
      'More mass means more force, but also more inertia - they cancel.',
      'Predict the vacuum case, then check it.',
    ] },

  { code: 'PHYS_THIRD_LAW_SAME_OBJECT', label: 'Action and reaction applied to the same object',
    concept: 'newtons-third-law', subject: 'physics', severity: 'moderate', detector: 'hybrid',
    description: 'The pair of forces is thought to cancel, so nothing should ever accelerate.',
    strategy: 'label_the_pair',
    steps: [
      'Write each force as "A on B". The pair is "A on B" and "B on A".',
      'They act on different objects, so they never cancel for one object.',
      'Draw separate free-body diagrams for each object.',
    ] },

  { code: 'PHYS_HEAT_IS_TEMPERATURE', label: 'Heat and temperature are the same thing',
    concept: 'temperature', subject: 'physics', severity: 'moderate', detector: 'hybrid',
    description: 'A big warm object is assumed to be hotter than a small hot one because it holds more energy.',
    strategy: 'intensive_vs_extensive',
    steps: [
      'A sparkler is thousands of degrees but cannot heat a bath. Why?',
      'Temperature is average energy per particle; heat is total energy transferred.',
      'Compare a cup and a bathtub at the same temperature.',
    ] },

  { code: 'PHYS_CURRENT_USED_UP', label: 'Current is used up as it goes round a circuit',
    concept: 'circuits', subject: 'physics', severity: 'critical', detector: 'hybrid',
    description: 'The bulb is thought to consume current, so less returns to the battery.',
    strategy: 'bicycle_chain',
    steps: [
      'A circuit is a bicycle chain: every link moves at once, none disappears.',
      'Energy is transferred at the bulb; charge is not consumed.',
      'Measure current before and after the bulb and compare.',
    ],
    wrong: 'Current is smaller after the bulb', right: 'Current is the same everywhere in a series loop; energy is what is transferred' },

  { code: 'BIO_PLANTS_EAT_SOIL', label: 'Plants get their food from the soil',
    concept: 'photosynthesis', subject: 'biology', severity: 'moderate', detector: 'hybrid',
    description: 'Soil is treated as plant food, so the carbon source for plant mass is missed.',
    strategy: 'mass_accounting',
    steps: [
      'Where does the mass of a tree come from? Weigh the soil before and after.',
      'Most of the mass arrives as carbon dioxide from the air.',
      'Soil supplies water and minerals, not energy or bulk carbon.',
    ] },

  { code: 'BIO_RESP_IS_BREATHING', label: 'Respiration means breathing',
    concept: 'respiration', subject: 'biology', severity: 'moderate', detector: 'rule',
    description: 'Cellular respiration is confused with ventilation, so plants are thought not to respire.',
    strategy: 'scale_separation',
    steps: [
      'Breathing moves air. Respiration happens inside every cell, every second.',
      'Plants respire too - day and night - as well as photosynthesising.',
      'Label a diagram at both scales: organism and cell.',
    ] },

  { code: 'BIO_DOMINANT_MEANS_COMMON', label: 'Dominant alleles are the most common',
    concept: 'inheritance', subject: 'biology', severity: 'minor', detector: 'hybrid',
    description: '"Dominant" is read as "frequent in the population" rather than "expressed when present".',
    strategy: 'definition_split',
    steps: [
      'Dominance is about expression in one individual, not frequency in a population.',
      'Find a rare dominant trait and a common recessive one.',
      'Re-read the definition and restate it in your own words.',
    ] },

  { code: 'EARTH_SEASONS_DISTANCE', label: 'Seasons are caused by distance from the Sun',
    concept: 'seasons', subject: 'earth_science', severity: 'moderate', detector: 'hybrid',
    description: 'Earth is thought to be closer to the Sun in summer, which cannot explain opposite hemispheres.',
    strategy: 'hemisphere_contradiction',
    steps: [
      'If distance caused seasons, both hemispheres would have summer together. They do not.',
      'Tilt a globe under a lamp and measure the light spread per unit area.',
      'Note that Earth is actually slightly farther from the Sun in July.',
    ],
    wrong: 'It is summer because Earth is closer to the Sun',
    right: 'It is summer because your hemisphere is tilted toward the Sun, spreading light over less area' },

  { code: 'CHEM_MASS_LOST_IN_REACTION', label: 'Mass disappears when a gas is produced',
    concept: 'conservation-mass', subject: 'chemistry', severity: 'moderate', detector: 'rule',
    description: 'An open-container reaction appears to lose mass, so conservation is thought to fail.',
    strategy: 'closed_system',
    steps: [
      'Repeat the reaction in a sealed container and weigh it again.',
      'The gas still has mass - it just left the balance.',
      'Count atoms on both sides of the equation.',
    ] },

  { code: 'CHEM_UNBALANCED_SUBSCRIPTS', label: 'Balancing equations by changing subscripts',
    concept: 'balancing-equations', subject: 'chemistry', severity: 'critical', detector: 'rule',
    description: 'Subscripts are altered to balance atom counts, which silently changes the substance.',
    strategy: 'identity_preservation',
    steps: [
      'Changing H2O to H2O2 makes a different chemical, not a balanced equation.',
      'Only coefficients - the big numbers in front - may change.',
      'Rebuild the equation using a count table per element.',
    ],
    wrong: 'H2 + O2 -> H2O2', right: '2H2 + O2 -> 2H2O' },

  { code: 'ENG_MAIN_IDEA_IS_FIRST_LINE', label: 'The main idea is always the first sentence',
    concept: 'main-idea', subject: 'english', severity: 'minor', detector: 'hybrid',
    description: 'The opening line is taken as the claim even when it is a hook or a counter-point.',
    strategy: 'claim_hunt',
    steps: [
      'Ask what the whole paragraph is trying to convince you of.',
      'Delete each sentence in turn: which loss breaks the paragraph?',
      'Find a paragraph where the main idea arrives last.',
    ] },
];

/** Seed practice items. Distractors are tied to misconception codes, so a wrong
 *  answer is a diagnosis rather than a mark. */
export interface SeedItem {
  concept: string;
  kind: 'mcq' | 'numeric' | 'short_answer' | 'true_false';
  stem: string;
  choices?: { key: string; text: string; misconceptionCode?: string }[];
  answer: unknown;
  difficulty: number;
  discrimination?: number;
  bloom?: Bloom;
}

export const SEED_ITEMS: SeedItem[] = [
  { concept: 'fraction-addition', kind: 'mcq', difficulty: 0.1, discrimination: 1.4,
    stem: 'What is 2/3 + 1/4?',
    choices: [
      { key: 'a', text: '11/12' },
      { key: 'b', text: '3/7', misconceptionCode: 'FRAC_ADD_CROSS' },
      { key: 'c', text: '3/12' },
      { key: 'd', text: '2/12' },
    ], answer: 'a' },
  { concept: 'fraction-addition', kind: 'numeric', difficulty: -0.3, discrimination: 1.1,
    stem: 'Add 1/2 + 1/2 and give your answer as a decimal.', answer: 1 },
  { concept: 'fractions', kind: 'mcq', difficulty: -0.6, discrimination: 1.2,
    stem: 'Which fraction is larger: 1/3 or 1/8?',
    choices: [
      { key: 'a', text: '1/3' },
      { key: 'b', text: '1/8', misconceptionCode: 'FRAC_BIGGER_DENOM' },
      { key: 'c', text: 'They are equal' },
    ], answer: 'a' },
  { concept: 'decimals', kind: 'mcq', difficulty: -0.4, discrimination: 1.3,
    stem: 'Which number is larger: 0.4 or 0.125?',
    choices: [
      { key: 'a', text: '0.4' },
      { key: 'b', text: '0.125', misconceptionCode: 'DEC_LONGER_BIGGER' },
    ], answer: 'a' },
  { concept: 'order-of-operations', kind: 'mcq', difficulty: -0.2, discrimination: 1.5,
    stem: 'Evaluate 2 + 3 x 4.',
    choices: [
      { key: 'a', text: '14' },
      { key: 'b', text: '20', misconceptionCode: 'PEMDAS_LEFT_RIGHT' },
      { key: 'c', text: '24' },
    ], answer: 'a' },
  { concept: 'integers', kind: 'numeric', difficulty: 0.2, discrimination: 1.2,
    stem: 'What is 5 - (-3)?', answer: 8 },
  { concept: 'linear-equations', kind: 'numeric', difficulty: 0.4, discrimination: 1.6,
    stem: 'Solve for x: 2x + 3 = 11', answer: 4 },
  { concept: 'proportions', kind: 'mcq', difficulty: 0.5, discrimination: 1.4,
    stem: 'A recipe for 2 people needs 4 cups of flour. How much for 3 people?',
    choices: [
      { key: 'a', text: '6 cups' },
      { key: 'b', text: '5 cups', misconceptionCode: 'PROP_ADDITIVE' },
      { key: 'c', text: '8 cups' },
    ], answer: 'a' },
  { concept: 'newtons-first-law', kind: 'mcq', difficulty: 0.6, discrimination: 1.5,
    stem: 'A hockey puck slides across frictionless ice at a steady speed. What is the net force on it?',
    choices: [
      { key: 'a', text: 'Zero' },
      { key: 'b', text: 'A constant forward force', misconceptionCode: 'PHYS_FORCE_NEEDED_FOR_MOTION' },
      { key: 'c', text: 'A force that decreases over time' },
    ], answer: 'a' },
  { concept: 'circuits', kind: 'mcq', difficulty: 0.55, discrimination: 1.4,
    stem: 'In a simple series circuit with one bulb, how does the current after the bulb compare with the current before it?',
    choices: [
      { key: 'a', text: 'It is the same' },
      { key: 'b', text: 'It is smaller, because the bulb uses some up', misconceptionCode: 'PHYS_CURRENT_USED_UP' },
      { key: 'c', text: 'It is larger' },
    ], answer: 'a' },
  { concept: 'seasons', kind: 'mcq', difficulty: 0.3, discrimination: 1.3,
    stem: 'Why is it summer in the northern hemisphere in July?',
    choices: [
      { key: 'a', text: 'The northern hemisphere is tilted toward the Sun' },
      { key: 'b', text: 'Earth is closest to the Sun in July', misconceptionCode: 'EARTH_SEASONS_DISTANCE' },
      { key: 'c', text: 'The Sun produces more energy in July' },
    ], answer: 'a' },
  { concept: 'photosynthesis', kind: 'mcq', difficulty: 0.25, discrimination: 1.3,
    stem: 'Where does most of the mass of a large tree originally come from?',
    choices: [
      { key: 'a', text: 'Carbon dioxide in the air' },
      { key: 'b', text: 'The soil it grew in', misconceptionCode: 'BIO_PLANTS_EAT_SOIL' },
      { key: 'c', text: 'Water alone' },
    ], answer: 'a' },
  { concept: 'balancing-equations', kind: 'mcq', difficulty: 0.7, discrimination: 1.5,
    stem: 'Which is the correctly balanced equation for hydrogen burning in oxygen?',
    choices: [
      { key: 'a', text: '2H2 + O2 -> 2H2O' },
      { key: 'b', text: 'H2 + O2 -> H2O2', misconceptionCode: 'CHEM_UNBALANCED_SUBSCRIPTS' },
      { key: 'c', text: 'H2 + O2 -> H2O' },
    ], answer: 'a' },
  { concept: 'perimeter-area', kind: 'numeric', difficulty: -0.1, discrimination: 1.1,
    stem: 'A rectangle is 5 cm by 3 cm. What is its area in square centimetres?', answer: 15 },
  { concept: 'pythagoras', kind: 'numeric', difficulty: 0.65, discrimination: 1.5,
    stem: 'A right triangle has legs of 3 and 4. How long is the hypotenuse?', answer: 5 },
  { concept: 'ohms-law', kind: 'numeric', difficulty: 0.6, discrimination: 1.4,
    stem: 'A 12 V battery drives 3 A through a resistor. What is the resistance in ohms?', answer: 4 },
  { concept: 'punnett-squares', kind: 'mcq', difficulty: 0.6, discrimination: 1.3,
    stem: 'Two heterozygous parents (Aa x Aa) have a child. What is the probability the child shows the recessive trait?',
    choices: [
      { key: 'a', text: '1/4' },
      { key: 'b', text: '1/2' },
      { key: 'c', text: '0, because A is dominant', misconceptionCode: 'BIO_DOMINANT_MEANS_COMMON' },
    ], answer: 'a' },
  { concept: 'mean-median-mode', kind: 'numeric', difficulty: 0.1, discrimination: 1.0,
    stem: 'What is the median of 2, 3, 4, 5, 100?', answer: 4 },
];
